-- run with admin user
DROP DATABASE IF EXISTS $name$_db;
DROP ROLE IF EXISTS $name$_db;

DO
\$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM  pg_catalog.pg_roles WHERE rolname = '$name$_db') THEN CREATE ROLE $name$_db;
    END IF;
    ALTER ROLE $name$_db WITH PASSWORD '$name$' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN;
  END
\$\$;

CREATE DATABASE $name$_db OWNER $name$_db ENCODING "utf8";

CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS btree_gin;