-- run with app user
CREATE SCHEMA IF NOT EXISTS $name$ AUTHORIZATION $name$_db;

ALTER ROLE "$name$_db" SET search_path TO $name$, public;
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS btree_gin;